### PR TITLE
don't require emulator version to start with 0 (fixes #123)

### LINKED ISSUE #123: fix the logic to check new emus version
Looking at the [`RA_CheckForUpdate()` in `RA_Core.cpp`](https://github.com/RetroAchievements/RAIntegration/blob/73cfb9689cc2c402294776bb48eb61421ffe294d/src/RA_Core.cpp#L902), it seems that the logic only recognize versions starting with `0.`.

This method is unable to handle RALibretro's versions (currently 1.0.12).

Related to RetroAchievements/RALibretro#25.

### PR DESCRIPTION
**Pull request by Jamiras**
also fixes "Check for Updates" menu option to support JSON payload

### CODE REVIEW

**Comment by meleu** [comment]
hey @Jamiras,
Is this change making RAIntegration able to recognize the difference between `1.0.7` and `1.0.12`, for example?

**Comment by Jamiras** [comment]
Yes. Support for full four-digit client versions.

I think it's ready to go, but it will benefit from the "e=" API change. I've been waiting for that to be deployed, but could just as easily make that change later.

**Comment by meleu** [comment]
oh! I think I forgot to make you aware, but that change in the API was already deployed. Sorry about that!

Look how it behaves:

**Using `e=`, for emulatorID**:
```
http://retroachievements.org/dorequest.php?r=latestclient&e=1
{"Success":true,"LatestVersion":"0.059"}

http://retroachievements.org/dorequest.php?r=latestclient&e=2
{"Success":true,"LatestVersion":"0.025"}

http://retroachievements.org/dorequest.php?r=latestclient&e=3
{"Success":true,"LatestVersion":"0.055"}

http://retroachievements.org/dorequest.php?r=latestclient&e=4
{"Success":false,"Error":"Unknown client! (EmulatorID: 4)"}

http://retroachievements.org/dorequest.php?r=latestclient&e=5
{"Success":true,"LatestVersion":"0.014"}

http://retroachievements.org/dorequest.php?r=latestclient&e=6
{"Success":true,"LatestVersion":"0.002"}

http://retroachievements.org/dorequest.php?r=latestclient&e=7
{"Success":false,"Error":"Unknown client! (File not found: LatestRALibretroVersion.html)"}

http://retroachievements.org/dorequest.php?r=latestclient&e=8
{"Success":true,"LatestVersion":"0.022"}

http://retroachievements.org/dorequest.php?r=latestclient&e=9
{"Success":false,"Error":"Unknown client! (EmulatorID: 9)"}

http://retroachievements.org/dorequest.php?r=latestclient&e=10
{"Success":false,"Error":"Unknown client! (EmulatorID: 10)"}
```

**Using `c=`, for consoleID**:
```
http://retroachievements.org/dorequest.php?r=latestclient&c=1
{"Success":true,"LatestVersion":"0.057"}

http://retroachievements.org/dorequest.php?r=latestclient&c=2
{"Success":true,"LatestVersion":"0.059"}

http://retroachievements.org/dorequest.php?r=latestclient&c=3
{"Success":true,"LatestVersion":"0.025"}

http://retroachievements.org/dorequest.php?r=latestclient&c=4
{"Success":true,"LatestVersion":"0.055"}

http://retroachievements.org/dorequest.php?r=latestclient&c=5
{"Success":false,"Error":"Unknown client! (ConsoleID: 5)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=6
{"Success":false,"Error":"Unknown client! (ConsoleID: 6)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=7
{"Success":true,"LatestVersion":"0.014"}

http://retroachievements.org/dorequest.php?r=latestclient&c=8
{"Success":true,"LatestVersion":"0.002"}

http://retroachievements.org/dorequest.php?r=latestclient&c=9
{"Success":false,"Error":"Unknown client! (ConsoleID: 9)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=10
{"Success":false,"Error":"Unknown client! (ConsoleID: 10)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=11
{"Success":true,"LatestVersion":"0.022"}

http://retroachievements.org/dorequest.php?r=latestclient&c=12
{"Success":false,"Error":"Unknown client! (ConsoleID: 12)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=13
{"Success":false,"Error":"Unknown client! (ConsoleID: 13)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=14
{"Success":false,"Error":"Unknown client! (ConsoleID: 14)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=15
{"Success":false,"Error":"Unknown client! (ConsoleID: 15)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=16
{"Success":false,"Error":"Unknown client! (ConsoleID: 16)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=17
{"Success":false,"Error":"Unknown client! (ConsoleID: 17)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=18
{"Success":false,"Error":"Unknown client! (ConsoleID: 18)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=19
{"Success":false,"Error":"Unknown client! (ConsoleID: 19)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=20
{"Success":false,"Error":"Unknown client! (ConsoleID: 20)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=21
{"Success":false,"Error":"Unknown client! (ConsoleID: 21)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=22
{"Success":false,"Error":"Unknown client! (ConsoleID: 22)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=23
{"Success":false,"Error":"Unknown client! (ConsoleID: 23)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=24
{"Success":false,"Error":"Unknown client! (ConsoleID: 24)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=25
{"Success":false,"Error":"Unknown client! (File not found: LatestRALibretroVersion.html)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=26
{"Success":false,"Error":"Unknown client! (ConsoleID: 26)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=27
{"Success":false,"Error":"Unknown client! (ConsoleID: 27)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=28
{"Success":false,"Error":"Unknown client! (ConsoleID: 28)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=29
{"Success":false,"Error":"Unknown client! (ConsoleID: 29)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=30
{"Success":false,"Error":"Unknown client! (ConsoleID: 30)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=31
{"Success":false,"Error":"Unknown client! (ConsoleID: 31)"}

http://retroachievements.org/dorequest.php?r=latestclient&c=32
{"Success":false,"Error":"Unknown client! (ConsoleID: 32)"}
```

**Comment by meleu** [comment]
by the way, I'm going to put RALibretro 1.0.7 on the server. Will keep the `LatestRALibretroVersion.html` as `1.0.7` for now.

@leiradel said he'll be able to solve the last issues in the Sunday.

**Pull request merged**
