### PR TITLE
URL escape password before sending login request

### LINKED ISSUE #114: Passwords are not URL-escaped
I wasn't able to log in to RA through any of the emulator apps, so I changed my password to a simple one. I was able to log in with this simple password. After changing my password back to a more complex one, I wasn't able to log in again. This made me think it was an issue with not escaping special characters on the login request. I skimmed the source code, and saw that passwords are sent as-is without any checks to see if the characters are valid URL characters. Sure enough, after manually escaping my password and pasting the escaped version into RAIntegration's password field, I was able to log in.

For clarification, please consider the following example:

Let's say this string is my password (it's not my real password!): s3?AJhs:u+S=D<%-]@{O

If I use this string as-is in RAIntegration, my login will fail, even though I would be able to log in to RetroAchievements.org with this very password.

However, if I enter an _**escaped**_ version into RAIntegration, my login will succeed without issue. So my above password would become:

s3%3FAJhs%3Au%2BS%3DD%3C%25-%5D%40%7BO

So instead of sending this request:

`https://retroachievements.org/login_app.php?u=ubergeek77&p=s3?AJhs:u+S=D<%-]@{O`

it sends this request:

`https://retroachievements.org/login_app.php?u=ubergeek77&p=s3%3FAJhs%3Au%2BS%3DD%3C%25-%5D%40%7BO`

and the server can properly read the password and send the appropriate response.

RAIntegration should really be doing this manually, as sending _**any**_ URL request before properly sanitizing it is bad practice.

### PR DESCRIPTION
**Pull request by ubergeek77**
Fixes #114

### CODE REVIEW

**Comment by SyrianBallaS** [comment]
A lot of stuff in boost already exists in the standard library. I'd suggest making it a submodule. 3rd party libs have a low chance of getting accepted, I think you should've made your case on discord first.

**Comment by ubergeek77** [comment]
No problem, I just noticed my issue wasn't getting any attention. I just thought I would help.

Although I shouldn't really need to "make a case" about this, considering the way passwords are currently handled is completely wrong.

**Comment by SyrianBallaS** [comment]
I meant if you absolutely need a 3rd party lib youd have to convince the others first mainly @scottfromderby. 

Help is always welcome.

**Comment by ubergeek77** [comment]
Ah, it looks like I caused a bit of confusion here. I am very sorry!

The boost stuff wasn't meant to be added to this PR. I only meant to add [4471eb2](https://github.com/RetroAchievements/RAIntegration/pull/116/commits/4471eb2344c8875112c152a53aff69ca75a5fdca), which only used built in stuff.

The rest of the commits were never intended to be referenced here. I only committed them to my own fork to help me keep track of what needed to be changed to work offline. I basically just wanted to "hack" RAIntegrations for my own personal use in order to work offline until #21 is completely done.

Everything other than the commit this was opened with is extremely dirty code and definitely shouldn't be committed!

**Comment by SyrianBallaS** [comment]
Dont worry about it too much. I'll look at your code properly later when I get to my laptop (using a phone) to see if it needs polish or not.

My main languages are .net/core related myself and haven't really used c/c++ extensively since university. You'll get back in the groove if you really want to. Good luck anway.

**Comment by meleu** [comment]
@ubergeek77 I liked the fix presented in commit 4471eb2. Feel free to submit another PR.

**Comment by Jamiras** [comment]
> I just noticed my issue wasn't getting any attention. I just thought I would help
It's only been three days. There are open PRs that I want to get merged before I start addressing anything else, and I'm out-of-town this weekend, so I haven't had a chance to look at the changes yet.

Even if we did merge this today, it would probably by 3-4 months before it's actually published to the site. This project isn't exactly on a fixed release cycle.

Having said that, I'm glad that you want to help. I'll take a look in a couple days.

**Pull request closed without merging**
