### PR TITLE
replace 100 frame delay with delayed activation logic (addresses #238)

### PR DESCRIPTION
**Pull request by Jamiras**

### CODE REVIEW

**Comment by kdecks** [comment]
this is great

**Comment by rzumer** [comment]
I'm not sure I understood your description of the behavior in #238, so would it not be a problem to remove the delay if memory is "initialized" twice? I have seen cases where the memory layout changes completely in multiple phases.

**Comment by Jamiras** [comment]
Memory can be initialized as many times as the emulator feels is necessary and whenever it feels like doing it. We can't control that. This code implements a solution that matches what RetroArch is doing on load to prevent triggers due to uninitialized memory. Upon load, all achievements are ignored until they evaluate false, at which point, they become eligible to trigger on the next frame. If re-initializing the memory causes an achievement to evaluate false, it will become eligible. If it has previously evaluated false and re-initialization causes it to evaluate true, it will trigger. 

By requiring the trigger to be false, we can prevent "on load" triggers from firing for as long as necessary. We don't have to guess if 10 frames is too little or 100 frames is too much.

There is similar behavior in the leaderboard code. The leaderboard cannot be reactivated after a cancel until the submit condition is false for at least one frame. This prevents reactivation in the middle of a challenge if the player fails it.

**Comment by rzumer** [comment]
Seems good to me, it is just worth keeping in mind that this might expose issues already present in RetroArch that were not visible in the standalone emulators and RALibretro.

**Pull request merged**
